# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    commandOptions: '-var client_id=$(CLIENT_ID)  -var client_secret=$(CLIENT_SECRET)'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(0c6b065f-5b32-47b7-b55f-6e6cbe2eb88c)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'newsA'
    backendAzureRmResourceGroupLocation: 'East Asia'
    backendAzureRmStorageAccountName: 'dsxswesz'
    backendAzureRmContainerName: 'dcsew'
    backendAzureRmKey: 'tfstate'
    allowTelemetryCollection: true